In [896]:
import pandas as pd
df = pd.read_json("../../data/beds.json")
df

,location_id,location_string,hl7_department,hl7_room,hl7_bed,department_id,room_id,bed_id,department,speciality,...,department_speciality,department_type,department_service_grouper,department_level_of_care_grouper,location_name,parent_location_name,closed,covid,xpos,ypos
0,11046,T06H^T06H BY04^BY04-22,T06H,T06H BY04,BY04-22,415468477,415468479,415468508,UCH T06 HEAD (T06H),Head and Neck - ENT,...,Head and Neck - ENT,HOD,Head &amp; Neck,Surgical,UNIVERSITY COLLEGE HOSPITAL CAMPUS,UCLH PARENT HOSPITAL,False,False,,
1,2278,T06G^T06G BY57^BY57-57,T06G,T06G BY57,BY57-57,415468456,415468669,415468671,UCH T06 GYNAE (T06G),Gynaecology - General,...,Gynaecology - General,HOD,Gynaecology,Surgical,UNIVERSITY COLLEGE HOSPITAL CAMPUS,UCLH PARENT HOSPITAL,False,False,,
2,2347,T07^T07N BY04^BY04-19,T07,T07N BY04,BY04-19,415468532,415468601,415468838,UCH T07 NORTH (T07N),General Surgery - General,...,General Surgery - General,HOD,GI &amp; General Surgery,Surgical,UNIVERSITY COLLEGE HOSPITAL CAMPUS,UCLH PARENT HOSPITAL,False,False,,
3,722,T10S^T10S BY07^BY07-34,T10S,T10S BY07,BY07-34,415469488,415469643,415469645,UCH T10 SOUTH (T10S),Geriatric Medicine - General,...,Geriatric Medicine - General,HOD,Trauma &amp; Orthopaedics,Surgical,UNIVERSITY COLLEGE HOSPITAL CAMPUS,UCLH PARENT HOSPITAL,False,False,,
4,1977,T10S^T10S BY07^BY07-35,T10S,T10S BY07,BY07-35,415469488,415469643,415469854,UCH T10 SOUTH (T10S),Geriatric Medicine - General,...,Geriatric Medicine - General,HOD,Trauma &amp; Orthopaedics,Surgical,UNIVERSITY COLLEGE HOSPITAL CAMPUS,UCLH PARENT HOSPITAL,False,False,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1409,392620360,T11E^T11E BY02^BY02-14,T11E,T11E BY02,BY02-14,415469625,415560265,415560313,UCH T11 EAST (T11E),Paediatric - Oncology,...,Paediatric - Oncology,HOD,*Unspecified,Paediatrics,UNIVERSITY COLLEGE HOSPITAL CAMPUS,UCLH PARENT HOSPITAL,False,False,,
1410,392634725,T11E^T11E BY02^BY02-11,T11E,T11E BY02,BY02-11,415469625,415560265,415560342,UCH T11 EAST (T11E),Paediatric - Oncology,...,Paediatric - Oncology,HOD,*Unspecified,Paediatrics,UNIVERSITY COLLEGE HOSPITAL CAMPUS,UCLH PARENT HOSPITAL,False,False,,
1411,392618556,T11E^T11E BY02^BY02-12,T11E,T11E BY02,BY02-12,415469625,415560265,415560345,UCH T11 EAST (T11E),Paediatric - Oncology,...,Paediatric - Oncology,HOD,*Unspecified,Paediatrics,UNIVERSITY COLLEGE HOSPITAL CAMPUS,UCLH PARENT HOSPITAL,False,False,,
1412,392622126,T11E^T11E BY02^BY02-16,T11E,T11E BY02,BY02-16,415469625,415560265,415560352,UCH T11 EAST (T11E),Paediatric - Oncology,...,Paediatric - Oncology,HOD,*Unspecified,Paediatrics,UNIVERSITY COLLEGE HOSPITAL CAMPUS,UCLH PARENT HOSPITAL,False,False,,
1413,544328250,1020100175^T16SW SR41^SR41-41,1020100175,T16SW SR41,SR41-41,555516423,555516425,555516427,UCH T16 SOUTH (T16S),Geriatric Medicine - General,...,Geriatric Medicine - General,HOD,Care of the Elderly,Medicine,UNIVERSITY COLLEGE HOSPITAL CAMPUS,UCLH PARENT HOSPITAL,False,False,,

In [897]:
df.sort_values(["department", "room", "hl7_bed"], inplace=True)

In [898]:
departments = df[["hl7_department", "department_id", "department", "department_external_name", "department_speciality", "department_service_grouper", "department_level_of_care_grouper", "location_name"]].drop_duplicates()

In [899]:
departments.sort_values("department", inplace=True)

In [900]:
departments.set_index("department", inplace=True)

In [901]:
departments.to_excel("department_defaults.xlsx")

Now hand edit the excel sheet
then save the result as json into initialise as department_defaults.json

In [902]:
# departments = pd.read_excel("department_defaults.xlsx")
# departments.to_json("department_defaults.json")

In [903]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1414 entries, 1131 to 56
Data columns (total 25 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   location_id                       1414 non-null   int64
 1   location_string                   1414 non-null   object
 2   hl7_department                    1414 non-null   object
 3   hl7_room                          1414 non-null   object
 4   hl7_bed                           1414 non-null   object
 5   department_id                     1414 non-null   int64
 6   room_id                           1414 non-null   int64
 7   bed_id                            1414 non-null   int64
 8   department                        1414 non-null   object
 9   speciality                        1414 non-null   object
 10  room                              1414 non-null   object
 11  department_name                   1414 non-null   object
 12  is_room                           1414 non-null   int64
 13  is_care_area                      1414 non-null   int64
 14  department_external_name          1414 non-null   object
 15  department_speciality             1414 non-null   object
 16  department_type                   1414 non-null   object
 17  department_service_grouper        1414 non-null   object
 18  department_level_of_care_grouper  1414 non-null   object
 19  location_name                     1414 non-null   object
 20  parent_location_name              1414 non-null   object
 21  closed                            1414 non-null   object
 22  covid                             1414 non-null   bool
 23  xpos                              1414 non-null   object
 24  ypos                              1414 non-null   object
dtypes: bool(1), int64(6), object(18)
memory usage: 277.6+ KB

In [904]:
bed_fields = [
    "department", "room", "hl7_bed",
    "location_id", "location_string",
    "hl7_department", "hl7_room",
    "department_id", "room_id", "bed_id",
]

In [905]:
beds = df[bed_fields]

So copying all the `_id` fields but note that these are no guaranteeed to remain constant. Ironically, I think that the **hl7** string is much more likely to remain fixed

In [906]:
beds

,department,room,hl7_bed,location_id,location_string,hl7_department,hl7_room,department_id,room_id,bed_id
1131,GWB L01 CRITICAL CARE,SR01,SR01-01,184850908,1021800003^GWB L01W SR01^SR01-01,1021800003,GWB L01W SR01,415542019,415542087,415542089
1128,GWB L01 CRITICAL CARE,SR02,SR02-02,184246759,1021800003^GWB L01W SR02^SR02-02,1021800003,GWB L01W SR02,415542019,415542041,415542043
1130,GWB L01 CRITICAL CARE,SR03,SR03-03,182833483,1021800003^GWB L01W SR03^SR03-03,1021800003,GWB L01W SR03,415542019,415542081,415542083
359,GWB L01 CRITICAL CARE,SR04,SR04-04,182494358,1021800003^GWB L01W SR04^SR04-04,1021800003,GWB L01W SR04,415542019,415542021,415542023
1129,GWB L01 CRITICAL CARE,SR05,SR05-05,187575160,1021800003^GWB L01W SR05^SR05-05,1021800003,GWB L01W SR05,415542019,415542063,415542065
...,...,...,...,...,...,...,...,...,...,...
221,WMS W04 WARD,SR20,SR20-20,1594690,WST4^W04W SR11^SR20-20,WST4,W04W SR11,415480675,415480696,415480698
119,WMS W04 WARD,SR21,SR21-21,382057,WST4^W04W SR12^SR21-21,WST4,W04W SR12,415480675,415480802,415480804
137,WMS W04 WARD,SR22,SR22-22,407619,WST4^W04W SR22^SR22-22,WST4,W04W SR22,415480675,415480790,415480792
106,WMS W04 WARD,SR23,SR23-23,243196,WST4^W04W SR23^SR23-23,WST4,W04W SR23,415480675,415480837,415480839
56,WMS W04 WARD,SR24,SR24-24,145411,WST4^W04W SR24^SR24-24,WST4,W04W SR24,415480675,415485028,415485030

In [907]:
beds[["bed_split_1", "bed_split_2"]] = beds["hl7_bed"].str.split("-", expand=True)

/var/folders/zc/nmxh55t94h30b0y1w6zs2r800000gn/T/ipykernel_45700/3814067030.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  beds[["bed_split_1", "bed_split_2"]] = beds["hl7_bed"].str.split("-", expand=True)
/var/folders/zc/nmxh55t94h30b0y1w6zs2r800000gn/T/ipykernel_45700/3814067030.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  beds[["bed_split_1", "bed_split_2"]] = beds["hl7_bed"].str.split("-", expand=True)

In [908]:
beds

,department,room,hl7_bed,location_id,location_string,hl7_department,hl7_room,department_id,room_id,bed_id,bed_split_1,bed_split_2
1131,GWB L01 CRITICAL CARE,SR01,SR01-01,184850908,1021800003^GWB L01W SR01^SR01-01,1021800003,GWB L01W SR01,415542019,415542087,415542089,SR01,01
1128,GWB L01 CRITICAL CARE,SR02,SR02-02,184246759,1021800003^GWB L01W SR02^SR02-02,1021800003,GWB L01W SR02,415542019,415542041,415542043,SR02,02
1130,GWB L01 CRITICAL CARE,SR03,SR03-03,182833483,1021800003^GWB L01W SR03^SR03-03,1021800003,GWB L01W SR03,415542019,415542081,415542083,SR03,03
359,GWB L01 CRITICAL CARE,SR04,SR04-04,182494358,1021800003^GWB L01W SR04^SR04-04,1021800003,GWB L01W SR04,415542019,415542021,415542023,SR04,04
1129,GWB L01 CRITICAL CARE,SR05,SR05-05,187575160,1021800003^GWB L01W SR05^SR05-05,1021800003,GWB L01W SR05,415542019,415542063,415542065,SR05,05
...,...,...,...,...,...,...,...,...,...,...,...,...
221,WMS W04 WARD,SR20,SR20-20,1594690,WST4^W04W SR11^SR20-20,WST4,W04W SR11,415480675,415480696,415480698,SR20,20
119,WMS W04 WARD,SR21,SR21-21,382057,WST4^W04W SR12^SR21-21,WST4,W04W SR12,415480675,415480802,415480804,SR21,21
137,WMS W04 WARD,SR22,SR22-22,407619,WST4^W04W SR22^SR22-22,WST4,W04W SR22,415480675,415480790,415480792,SR22,22
106,WMS W04 WARD,SR23,SR23-23,243196,WST4^W04W SR23^SR23-23,WST4,W04W SR23,415480675,415480837,415480839,SR23,23
56,WMS W04 WARD,SR24,SR24-24,145411,WST4^W04W SR24^SR24-24,WST4,W04W SR24,415480675,415485028,415485030,SR24,24

Now merge in departments to get 'floor' and then use floor to sort to create a floor_bed_index field

In [909]:
departments = pd.read_json("department_defaults.json")
floors = departments.loc[:, ["department", "floor", "location_name"]]

In [910]:
beds = beds.merge(floors, how="left", on="department")

In [911]:
beds["bed_number"] = beds.loc[:,"bed_split_2"].str.extract('(\d+)')
beds.sort_values(["location_name", "floor", "department", "bed_number"], inplace=True, na_position="last")

!!dropping bed_index as I think this should be built dynamically in the application

use bed index and hand correct WMS floor 3 since this is the only floor that used '301' naming style for beds

perform the fillna with -1 _after_ the sort and the bed index is created so NaN values (those without bed numbers) go to the end; replace such numbers with NA

In [912]:
beds["bed_number"] = beds["bed_number"].fillna(-1).astype(int)
# beds["bed_index"] = beds["bed_index"].fillna(-1).astype(int)

In [913]:
beds.drop(columns=["bed_split_1", "bed_split_2"], inplace=True)

In [914]:
beds.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1414 entries, 0 to 1413
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   department       1414 non-null   object
 1   room             1414 non-null   object
 2   hl7_bed          1414 non-null   object
 3   location_id      1414 non-null   int64
 4   location_string  1414 non-null   object
 5   hl7_department   1414 non-null   object
 6   hl7_room         1414 non-null   object
 7   department_id    1414 non-null   int64
 8   room_id          1414 non-null   int64
 9   bed_id           1414 non-null   int64
 10  floor            1414 non-null   int64
 11  location_name    1414 non-null   object
 12  bed_number       1414 non-null   int64
dtypes: int64(6), object(7)
memory usage: 154.7+ KB

In [915]:
beds_defaults_icu = pd.read_json("bed_defaults_icu.json")
beds_defaults_icu.drop(columns=["department", "hl7_bed", "covid",], inplace=True)
beds_defaults_icu["closed"] = beds_defaults_icu["closed"].str.contains("True|1|TRUE")
beds_defaults_icu["xpos"] = beds_defaults_icu["xpos"].fillna(-1).astype(int)
beds_defaults_icu["ypos"] = beds_defaults_icu["ypos"].fillna(-1).astype(int)
beds_defaults_icu

     closed        location_string  xpos  ypos
0     False   T03^T03 BY01^BY01-11    70    30
1     False   T03^T03 BY01^BY01-12    80    30
2     False   T03^T03 BY01^BY01-14    90    30
3     False   T03^T03 BY01^BY01-15    80    40
4     False   T03^T03 BY01^BY01-16    70    40
..      ...                    ...   ...   ...
132    True  T01^T01 BY03^BY02-26G    -1    -1
133    True  T01^T01 BY03^BY02-27G    -1    -1
134    True  T01^T01 BY03^BY02-28G    -1    -1
135    True  T01^T01 BY03^BY02-29G    -1    -1
136    True  T01^T01 BY03^BY02-30G    -1    -1

[137 rows x 4 columns]

In [916]:
beds = beds.merge(beds_defaults_icu, on="location_string", how="left")
beds["closed"].fillna(False, inplace=True)

In [917]:
beds.to_excel("bed_defaults.xlsx", index=False)

Now hand edit if you wish, read back in, and then save as json

In [918]:
# beds = pd.read_excel("bed_defaults.xlsx")
beds["xpos"] = beds["xpos"].fillna(-1).astype(int)
beds["ypos"] = beds["ypos"].fillna(-1).astype(int)

In [919]:
beds.loc[beds["bed_number"] == -1, "closed"] = True

In [920]:
beds.to_json("bed_defaults.json", orient="records")

In [921]:
beds[:200]

,department,room,hl7_bed,location_id,location_string,hl7_department,hl7_room,department_id,room_id,bed_id,floor,location_name,bed_number,closed,xpos,ypos
0,GWB L01 CRITICAL CARE,SR01,SR01-01,184850908,1021800003^GWB L01W SR01^SR01-01,1021800003,GWB L01W SR01,415542019,415542087,415542089,1,GRAFTON WAY BUILDING,1,False,10,10
1,GWB L01 CRITICAL CARE,SR02,SR02-02,184246759,1021800003^GWB L01W SR02^SR02-02,1021800003,GWB L01W SR02,415542019,415542041,415542043,1,GRAFTON WAY BUILDING,2,False,30,10
2,GWB L01 CRITICAL CARE,SR03,SR03-03,182833483,1021800003^GWB L01W SR03^SR03-03,1021800003,GWB L01W SR03,415542019,415542081,415542083,1,GRAFTON WAY BUILDING,3,False,40,10
3,GWB L01 CRITICAL CARE,SR04,SR04-04,182494358,1021800003^GWB L01W SR04^SR04-04,1021800003,GWB L01W SR04,415542019,415542021,415542023,1,GRAFTON WAY BUILDING,4,False,60,10
4,GWB L01 CRITICAL CARE,SR05,SR05-05,187575160,1021800003^GWB L01W SR05^SR05-05,1021800003,GWB L01W SR05,415542019,415542063,415542065,1,GRAFTON WAY BUILDING,5,False,70,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,NHNN Q1 LADY ANNE,BY03,BY03-16,415467486,LYNQ^Q1LAA BY03^BY03-16,LYNQ,Q1LAA BY03,415467002,415467306,415467487,1,QUEEN SQUARE CAMPUS,16,False,-1,-1
196,NHNN Q1 LADY ANNE,BY03,BY03-17,415467516,LYNQ^Q1LAA BY03^BY03-17,LYNQ,Q1LAA BY03,415467002,415467306,415467517,1,QUEEN SQUARE CAMPUS,17,False,-1,-1
197,NHNN Q1 LADY ANNE,BY03,BY03-18,17036508,LYNQ^Q1LAA BY03^BY03-18,LYNQ,Q1LAA BY03,415467002,415467306,415467546,1,QUEEN SQUARE CAMPUS,18,False,-1,-1
198,NHNN Q1 LADY ANNE,BY04,BY04-19,36248824,LYNQ^Q1LAA BY04^BY04-19,LYNQ,Q1LAA BY04,415467002,415467168,415467371,1,QUEEN SQUARE CAMPUS,19,False,-1,-1
199,NHNN Q1 LADY ANNE,BY04,BY04-20,415467399,LYNQ^Q1LAA BY04^BY04-20,LYNQ,Q1LAA BY04,415467002,415467168,415467400,1,QUEEN SQUARE CAMPUS,20,False,-1,-1

In [922]:
beds[200:].shape

(1214, 16)

looks like this might work if I use `shift-i` (i.e. **I**) to enter *insert* mode